insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (1, 22, 'Green Butchers, The (Grønne slagtere, De)', 1873, 'horror', 18);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (2, 1, 'Metropolitan', 2020, 'fantasy', 7);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (3, 78, 'Dickson Experimental Sound Film', 1891, 'comedy', 3);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (4, 4, 'Rocks in my Pockets', 1902, 'drama', 10);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (5, 66, 'Stand by Me Doraemon', 1881, 'romance', 18);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (6, 94, 'Hit the Bank (Vabank)', 2013, 'sci-fi', 7);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (7, 50, 'Dante''s Peak', 1958, 'horror', 3);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (8, 35, 'The Land Before Time X: The Great Longneck Migration', 1817, 'sci-fi', 17);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (9, 71, 'Lords of Dogtown', 1821, 'action', 1);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (10, 74, 'Bless Me, Ultima', 1927, 'thriller', 17);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (11, 57, 'Still Walking (Aruitemo aruitemo)', 1923, 'sci-fi', 12);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (12, 15, 'From Paris with Love', 2020, 'action', 11);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (13, 4, 'Apocalypto', 1862, 'fantasy', 15);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (14, 77, 'Complete History of My Sexual Failures, A', 1874, 'thriller', 18);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (15, 46, 'Guelwaar', 1916, 'fantasy', 8);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (16, 11, 'American Heart', 1931, 'horror', 18);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (17, 13, 'Illusionist, The', 1870, 'drama', 16);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (18, 69, 'Bridget Jones: The Edge of Reason', 1874, 'action', 9);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (19, 28, 'Vantage Point', 1850, 'sci-fi', 3);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (20, 12, 'But I''m a Cheerleader', 1854, 'action', 15);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (21, 66, 'Starship Troopers 3: Marauder', 1884, 'mystery', 7);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (22, 97, 'Kabhi Haan Kabhi Naa', 1860, 'romance', 19);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (23, 41, 'Rape of Europa, The', 2008, 'thriller', 19);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (24, 79, 'Still Crazy', 1980, 'fantasy', 11);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (25, 12, 'Greystoke: The Legend of Tarzan, Lord of the Apes', 1882, 'fantasy', 16);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (26, 97, 'Gentlemen Broncos', 1826, 'documentary', 18);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (27, 96, 'Entr''acte', 1898, 'comedy', 14);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (28, 66, 'Our Little Differences (Die feinen Unterschiede)', 1877, 'horror', 10);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (29, 70, 'Independencia', 1853, 'romance', 7);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (30, 78, 'Golden Boys, The', 1915, 'horror', 19);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (31, 49, 'Stand by for Action', 2009, 'sci-fi', 13);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (32, 7, '35 and Ticking', 2000, 'action', 16);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (33, 3, 'Basket Case', 1911, 'sci-fi', 4);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (34, 51, 'Cuba', 2006, 'comedy', 16);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (35, 41, 'Film ist. 7-12', 1867, 'sci-fi', 5);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (36, 57, 'Cross My Heart', 1903, 'romance', 12);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (37, 12, 'Dangerous Moves (La diagonale du fou)', 2018, 'romance', 9);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (38, 22, 'Un vampiro para dos', 1890, 'action', 6);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (39, 25, 'Vanilla Sky', 1962, 'romance', 12);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (40, 100, 'Sister Street Fighter (Onna hissatsu ken)', 1886, 'mystery', 20);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (41, 45, 'Not One Less (Yi ge dou bu neng shao)', 1876, 'documentary', 12);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (42, 50, 'All Is Forgiven (Tout est pardonné)', 1971, 'horror', 16);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (43, 14, 'Ingeborg Holm', 1926, 'thriller', 1);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (44, 42, 'Law of Enclosures, The', 1973, 'documentary', 11);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (45, 89, 'Soft Skin, The (La peau douce)', 1900, 'action', 10);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (46, 24, 'Lightnin''', 2008, 'action', 10);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (47, 9, 'Catfish in Black Bean Sauce', 1831, 'sci-fi', 16);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (48, 100, 'Après lui', 1915, 'fantasy', 14);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (49, 72, 'Who Pulled the Plug? (Göta kanal eller Vem drog ur proppen?)', 1931, 'sci-fi', 8);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (50, 43, 'Last Call (Hoogste tijd)', 1860, 'drama', 19);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (51, 32, 'My Life as McDull (Mak dau goo si)', 1827, 'thriller', 11);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (52, 69, 'Mother and Son (Mat i syn)', 1870, 'thriller', 1);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (53, 85, 'Mad Dog Coll', 1870, 'mystery', 9);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (54, 30, 'Bloodhounds of Broadway', 1844, 'documentary', 3);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (55, 74, 'Wonder Bar', 1830, 'romance', 13);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (56, 52, 'Kismet', 1983, 'drama', 5);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (57, 43, 'Let Sleeping Corpses Lie (Non si deve profanare il sonno dei morti)', 1984, 'romance', 17);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (58, 19, 'Blue Juice', 1870, 'romance', 2);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (59, 48, 'Hollywood Ending', 1985, 'documentary', 7);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (60, 79, 'Wagon Master', 1816, 'mystery', 7);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (61, 43, 'Milk and Honey', 1985, 'sci-fi', 11);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (62, 43, 'Zero Hour!', 1892, 'comedy', 13);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (63, 20, 'Oblivion', 1922, 'thriller', 5);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (64, 96, 'Dread', 1980, 'action', 5);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (65, 87, 'Kiss for Corliss, A (Almost a Bride)', 2019, 'sci-fi', 19);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (66, 79, 'Thunderbolt and Lightfoot', 1926, 'mystery', 10);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (67, 100, 'Reagan', 1907, 'romance', 17);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (68, 85, 'You''re a Big Boy Now', 1954, 'action', 17);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (69, 96, 'Emitai', 1910, 'fantasy', 2);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (70, 67, 'Molly', 1977, 'comedy', 18);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (71, 1, 'Lower City (Cidade Baixa)', 1853, 'fantasy', 1);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (72, 45, 'Vicious Kind, The', 1964, 'thriller', 11);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (73, 49, 'Power/Rangers', 1986, 'documentary', 3);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (74, 74, 'Phantom Lover, The (Ye ban ge sheng)', 1948, 'documentary', 5);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (75, 91, 'My Favorite Blonde', 1883, 'romance', 1);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (76, 42, 'God Bless Ozzy Osbourne', 2014, 'fantasy', 5);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (77, 5, 'Seal Team Eight: Behind Enemy Lines', 1872, 'fantasy', 7);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (78, 15, 'Mahjong (Ma jiang)', 1826, 'drama', 3);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (79, 74, 'Christmas at Pee Wee''s Playhouse (a.k.a. Pee-Wee''s Playhouse Christmas Special)', 1822, 'documentary', 10);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (80, 28, 'Gremlins', 1804, 'thriller', 9);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (81, 60, 'Science and Islam', 1961, 'fantasy', 10);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (82, 44, 'Blood', 1995, 'thriller', 20);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (83, 21, 'Presentation, or Charlotte and Her Steak (Présentation ou Charlotte et son steak)', 1992, 'sci-fi', 10);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (84, 89, 'Devil''s Diary', 1905, 'fantasy', 3);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (85, 14, 'New Age, The', 1965, 'documentary', 7);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (86, 7, 'Sunrise at Campobello', 1840, 'documentary', 8);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (87, 79, 'Apartment, The (Appartement, L'')', 1958, 'comedy', 4);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (88, 89, 'Buried Alive II', 1897, 'romance', 8);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (89, 6, 'Wild Bill', 1861, 'action', 5);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (90, 65, '1408', 1895, 'mystery', 10);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (91, 82, 'Mon Paradis - Der Winterpalast', 1862, 'comedy', 4);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (92, 37, 'Road to Perdition', 1880, 'action', 6);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (93, 2, 'Red Dwarf, The (Nain rouge, Le)', 1995, 'sci-fi', 1);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (94, 17, 'Khumba', 1990, 'action', 4);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (95, 12, 'Wuthering Heights', 1834, 'thriller', 11);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (96, 86, 'Nameless, The (Los sin nombre)', 1981, 'comedy', 2);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (97, 81, 'One Foot in Heaven', 2000, 'documentary', 9);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (98, 17, 'Last Shot, The', 1948, 'romance', 5);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (99, 18, 'Edward, My Son', 1952, 'thriller', 20);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (100, 24, 'High Road to China', 1851, 'horror', 12);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (101, 44, 'Evening Star, The', 2009, 'comedy', 10);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (102, 23, 'Strapped', 1965, 'sci-fi', 14);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (103, 11, 'Major League: Back to the Minors', 1948, 'drama', 16);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (104, 42, 'Thérèse', 1982, 'sci-fi', 12);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (105, 77, 'Wind That Shakes the Barley, The', 2010, 'thriller', 8);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (106, 18, 'Memento Mori (Yeogo goedam II)', 1922, 'thriller', 12);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (107, 11, 'Dawn Patrol, The (Flight Commander)', 1882, 'thriller', 20);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (108, 9, 'Darby O''Gill and the Little People', 1865, 'sci-fi', 17);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (109, 87, 'Elena and Her Men (Paris Does Strange Things) (Elena et les hommes)', 1834, 'thriller', 12);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (110, 78, 'Slingshot, The (Kådisbellan)', 1986, 'thriller', 8);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (111, 72, 'Ballistic: Ecks vs. Sever', 1934, 'horror', 14);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (112, 51, 'Tomb of Ligeia, The', 1857, 'documentary', 15);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (113, 97, 'Bad Education (La mala educación)', 1962, 'fantasy', 15);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (114, 96, 'Crossroads', 1902, 'comedy', 3);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (115, 41, 'Three Crowns of the Sailor (Les trois couronnes du matelot)', 1838, 'romance', 15);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (116, 97, 'Time Without Pity', 1914, 'horror', 12);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (117, 36, 'Ragamuffin', 1963, 'thriller', 17);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (118, 60, 'Adrenalin: Fear the Rush', 1932, 'sci-fi', 20);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (119, 47, 'Vacancy', 1911, 'sci-fi', 16);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (120, 84, 'Let''s Go to Prison', 2007, 'mystery', 20);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (121, 96, 'V.I.P.s, The', 1929, 'comedy', 18);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (122, 91, 'Paradise', 1899, 'mystery', 11);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (123, 96, 'Passion of Darkly Noon, The', 2022, 'sci-fi', 15);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (124, 6, 'Doodlebug', 1802, 'sci-fi', 15);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (125, 52, 'Strictly Sexual', 1855, 'horror', 20);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (126, 69, 'Gotti', 1911, 'mystery', 11);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (127, 43, 'We Are from the Future (My iz budushchego)', 1831, 'drama', 6);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (128, 80, 'Living Out Loud', 1943, 'horror', 8);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (129, 52, 'Major Payne', 1823, 'action', 14);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (130, 88, 'James Dean', 1878, 'mystery', 19);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (131, 35, 'Shara (Sharasojyu)', 2008, 'romance', 5);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (132, 58, 'Avengers, The', 1875, 'mystery', 10);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (133, 82, 'Antique (Sayangkoldong yangkwajajeom aentikeu)', 1877, 'thriller', 13);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (134, 67, 'Judex', 2001, 'drama', 20);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (135, 94, 'Encore', 1893, 'mystery', 10);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (136, 95, 'Nobody''s Baby', 1814, 'fantasy', 3);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (137, 90, 'Single Girl, A (Fille seule, La)', 1983, 'romance', 14);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (138, 7, 'Love! Valour! Compassion!', 1982, 'thriller', 15);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (139, 90, 'Way Back, The', 2006, 'drama', 10);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (140, 70, 'Cannonball Run, The', 1944, 'thriller', 16);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (141, 18, 'Something Ventured', 1935, 'mystery', 2);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (142, 17, 'Left Behind II: Tribulation Force', 1899, 'mystery', 15);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (143, 25, 'Unknown Soldier, The (Unbekannte Soldat, Der)', 1955, 'documentary', 14);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (144, 44, 'Begin Again', 1870, 'action', 18);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (145, 41, 'Three Musketeers, The', 1858, 'comedy', 3);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (146, 30, 'Animal Love (Tierische Liebe)', 1831, 'romance', 18);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (147, 66, 'Peanuts - Die Bank zahlt alles', 2010, 'action', 14);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (148, 52, 'Changeling', 1852, 'romance', 16);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (149, 98, 'Old Boy', 1883, 'thriller', 6);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (150, 2, 'Revenge of the Green Dragons', 1825, 'documentary', 6);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (151, 46, 'Private Function, A', 1866, 'comedy', 5);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (152, 33, 'Girl in the Cadillac', 2002, 'drama', 8);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (153, 87, 'Rainmaker, The', 1985, 'documentary', 12);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (154, 22, 'Oscar and Lucinda (a.k.a. Oscar & Lucinda)', 1953, 'mystery', 8);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (155, 19, 'Deuce Bigalow: European Gigolo', 1888, 'mystery', 13);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (156, 90, 'Dying of Laughter (Muertos de Risa)', 1948, 'romance', 13);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (157, 61, 'Young Man with a Horn', 1954, 'action', 19);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (158, 26, 'Nordkraft', 1881, 'horror', 13);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (159, 37, 'By the Pricking of My Thumbs (Mon petit doigt m''a dit...)', 2018, 'action', 8);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (160, 41, 'Miss Granny', 1985, 'drama', 15);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (161, 45, 'Beyond Justice', 1822, 'mystery', 12);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (162, 92, 'My Sister''s Keeper', 1813, 'mystery', 16);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (163, 38, 'Good Thief, The', 1864, 'thriller', 11);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (164, 10, 'Best Man, The', 1976, 'sci-fi', 20);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (165, 62, 'Uncertainty', 1805, 'sci-fi', 9);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (166, 100, 'Southern District (Zona Sur)', 2024, 'documentary', 17);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (167, 97, 'No One Knows About Persian Cats (Kasi az gorbehaye irani khabar nadareh)', 1829, 'comedy', 19);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (168, 58, 'Stand Off', 1852, 'action', 5);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (169, 69, 'What Price Glory', 1879, 'action', 3);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (170, 4, 'My Life in Orange (Sommer in Orange)', 1840, 'documentary', 20);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (171, 73, 'Coming Apart', 1982, 'drama', 18);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (172, 50, 'Business of Fancydancing, The', 1911, 'action', 9);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (173, 56, 'Wet Hot American Summer', 1826, 'mystery', 11);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (174, 72, 'Best Laid Plans', 1885, 'drama', 19);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (175, 29, 'Wizard of Oz, The', 1895, 'romance', 11);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (176, 60, 'They Call Me Bruce? (a.k.a. A Fistful of Chopsticks)', 1814, 'romance', 7);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (177, 5, 'Dr. Akagi (Kanzo sensei)', 1800, 'fantasy', 4);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (178, 2, 'Cremaster 5', 1839, 'comedy', 11);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (179, 80, 'Black God, White Devil (Deus e o Diabo na Terra do Sol)', 1998, 'action', 20);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (180, 55, 'Just Between Friends', 1880, 'horror', 19);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (181, 76, 'Gomorrah (Gomorra)', 1907, 'fantasy', 13);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (182, 56, 'Just 4 Kicks', 1812, 'drama', 12);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (183, 89, 'Seven Angry Men', 1856, 'fantasy', 12);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (184, 6, 'Best of Times, The (Mei li shi guang)', 1987, 'horror', 14);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (185, 32, 'Serial Mom', 1982, 'documentary', 3);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (186, 15, 'Waiting to Exhale', 1887, 'thriller', 4);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (187, 23, 'Penalty, The', 1888, 'mystery', 17);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (188, 4, 'Body Fat Index of Love', 1875, 'fantasy', 8);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (189, 95, 'Running on Empty', 2013, 'action', 18);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (190, 22, 'Loaded Weapon 1 (National Lampoon''s Loaded Weapon 1)', 1849, 'thriller', 11);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (191, 83, 'Vanishing on 7th Street', 1870, 'documentary', 7);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (192, 31, 'Perez.', 1926, 'action', 7);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (193, 76, 'Congress, The', 1906, 'horror', 11);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (194, 33, 'Texas Chainsaw Massacre, The', 2003, 'drama', 13);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (195, 24, 'Springsteen & I', 1951, 'romance', 3);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (196, 32, 'That''s Entertainment, Part II', 1904, 'sci-fi', 17);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (197, 93, 'Next Day Air', 1856, 'drama', 15);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (198, 60, 'Sin of Madelon Claudet, The', 1964, 'drama', 19);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (199, 5, '12:01', 1881, 'sci-fi', 11);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (200, 71, 'Wise Kids, The', 1854, 'comedy', 1);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (201, 10, 'Irony of Fate, or Enjoy Your Bath! (Ironiya sudby, ili S legkim parom!)', 1857, 'thriller', 2);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (202, 29, 'Stacy''s Knights', 1801, 'comedy', 11);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (203, 19, 'The Wedding Ringer', 1958, 'sci-fi', 1);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (204, 4, 'Starter for 10', 1815, 'comedy', 3);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (205, 98, 'Punk''s Dead: SLC Punk! 2', 2014, 'action', 8);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (206, 23, 'This Is My Life', 1874, 'documentary', 15);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (207, 20, 'Mr. Nanny', 1898, 'thriller', 6);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (208, 41, 'Lille Fridolf and I', 1879, 'drama', 14);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (209, 84, 'Winning Streak', 1985, 'horror', 17);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (210, 29, 'Hello Ladies: The Movie', 1912, 'fantasy', 2);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (211, 12, 'Thieves, The (Dodookdeul)', 1990, 'horror', 13);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (212, 34, 'Alien Predator (Mutant II) (Falling, The)', 1884, 'action', 1);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (213, 34, 'Adventures of Huckleberry Finn, The', 1804, 'mystery', 8);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (214, 10, 'Imagine: John Lennon', 2004, 'sci-fi', 13);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (215, 24, 'Quick and the Dead, The', 1939, 'fantasy', 20);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (216, 80, 'Flight from Death: The Quest for Immortality', 1837, 'sci-fi', 6);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (217, 66, 'Across the Wide Missouri', 2012, 'comedy', 15);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (218, 18, 'Giger''s Necronomicon', 1870, 'fantasy', 14);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (219, 45, 'Deadly Tower, The', 1908, 'documentary', 13);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (220, 27, 'Ingmar Bergman on Life and Work (Ingmar Bergman: Om liv och arbete)', 1905, 'thriller', 13);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (221, 82, 'Unthinkable', 1953, 'documentary', 12);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (222, 64, 'Modris', 1894, 'drama', 15);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (223, 78, 'Glimpse Inside the Mind of Charles Swan III, A', 1822, 'comedy', 18);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (224, 55, 'Shriek of the Mutilated', 1879, 'sci-fi', 20);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (225, 75, 'Shrek the Halls', 1977, 'fantasy', 2);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (226, 54, 'Nickelodeon', 1827, 'mystery', 4);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (227, 93, 'Invincible', 1995, 'drama', 11);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (228, 79, 'Salsa', 1818, 'action', 8);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (229, 47, 'After Porn Ends', 1805, 'fantasy', 3);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (230, 42, 'Ulysses (Ulisse)', 1966, 'documentary', 4);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (231, 15, 'God''s Little Acre', 1923, 'thriller', 13);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (232, 36, 'Buddy Buddy', 1848, 'action', 15);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (233, 51, 'O Lucky Man!', 1930, 'fantasy', 1);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (234, 79, 'One Way Passage', 1924, 'documentary', 2);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (235, 84, 'Cahill U.S. Marshal (Cahill: United States Marshal) (Wednesday Morning)', 1843, 'action', 10);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (236, 89, 'Black Fury', 2000, 'horror', 4);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (237, 42, 'Burke and Hare', 1957, 'comedy', 14);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (238, 66, 'File on Thelma Jordan, The', 1967, 'sci-fi', 19);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (239, 84, 'A Blank on the Map', 2007, 'sci-fi', 12);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (240, 83, 'Blackbird', 1805, 'romance', 5);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (241, 3, 'House Is Black, The', 1891, 'sci-fi', 7);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (242, 5, 'Cosmopolis', 2001, 'horror', 11);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (243, 95, 'PK', 1829, 'drama', 18);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (244, 76, 'Russia 88', 1844, 'comedy', 15);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (245, 25, 'Adrenaline Drive (Adorenarin doraibu)', 1849, 'drama', 14);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (246, 74, 'Terror on a Train (Time Bomb)', 1853, 'sci-fi', 4);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (247, 3, 'Shiver (Eskalofrío)', 2008, 'sci-fi', 18);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (248, 53, 'Still Bill', 1872, 'documentary', 20);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (249, 69, 'Once Upon a Forest', 1948, 'comedy', 4);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (250, 76, 'Miffo', 1842, 'drama', 18);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (251, 43, 'Bad Blood: A Cautionary Tale ', 1823, 'fantasy', 8);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (252, 5, 'The Return of Ringo', 1826, 'documentary', 15);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (253, 38, 'Carmen', 1860, 'comedy', 7);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (254, 24, 'Dance with the Devil (Perdita Durango)', 1944, 'mystery', 20);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (255, 11, 'Red Obession', 1831, 'drama', 9);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (256, 57, 'Whip Hand, The', 1871, 'drama', 20);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (257, 68, 'Alphaville (Alphaville, une étrange aventure de Lemmy Caution)', 1802, 'fantasy', 18);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (258, 65, 'Big Mommas: Like Father, Like Son', 2014, 'comedy', 8);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (259, 48, 'Prelude to War (Why We Fight, 1)', 1821, 'action', 9);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (260, 81, 'Miss March', 1829, 'drama', 7);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (261, 51, 'Goonies, The', 2002, 'romance', 20);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (262, 68, '40 Days and 40 Nights', 2006, 'comedy', 12);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (263, 23, 'On the Town', 1902, 'thriller', 4);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (264, 40, 'Burnt by the Sun 2 (Utomlyonnye solntsem 2)', 1929, 'mystery', 13);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (265, 50, 'The Karen Carpenter Story', 1899, 'fantasy', 6);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (266, 82, 'Dead Times (Temps morts, Les)', 1995, 'documentary', 6);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (267, 64, 'Angel on My Shoulder', 2016, 'fantasy', 12);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (268, 39, 'Shivers (They Came from Within)', 1827, 'documentary', 16);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (269, 79, 'Spaghetti West, The', 1867, 'documentary', 9);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (270, 11, 'Palais royal !', 1940, 'horror', 12);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (271, 43, 'A Christmas Kiss', 1889, 'fantasy', 4);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (272, 42, 'Aglaya', 1860, 'sci-fi', 9);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (273, 66, 'Blown Away', 1959, 'thriller', 5);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (274, 8, 'Joan Rivers: A Piece of Work', 1959, 'fantasy', 20);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (275, 22, 'No Place to Hide', 1905, 'documentary', 16);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (276, 55, 'Sea Wife', 1910, 'fantasy', 11);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (277, 26, 'The Black Rose', 1934, 'drama', 13);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (278, 63, 'Unforgettable Summer, An (Un été inoubliable)', 1935, 'horror', 8);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (279, 74, 'O Último Mergulho', 1808, 'fantasy', 7);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (280, 47, 'Parasite', 1848, 'sci-fi', 9);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (281, 55, 'Garlic Is As Good As Ten Mothers', 1889, 'mystery', 12);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (282, 28, 'Monk and the Fish, The (Le moine et le poisson)', 1855, 'romance', 8);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (283, 38, 'Wonder Bar', 1903, 'sci-fi', 15);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (284, 91, 'Little Miss Marker', 1923, 'horror', 10);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (285, 2, 'Gleaming the Cube', 1847, 'thriller', 6);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (286, 73, 'Racket, The', 1842, 'fantasy', 15);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (287, 1, 'Matrix, The', 1831, 'romance', 16);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (288, 47, 'Severance', 1985, 'drama', 4);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (289, 84, 'Jack Frost', 1987, 'sci-fi', 20);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (290, 50, 'Sinivalkoinen valhe', 1806, 'romance', 7);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (291, 28, 'Naked Face, The', 1994, 'horror', 18);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (292, 50, 'Secret of the Wings', 1925, 'romance', 8);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (293, 90, 'Waco: The Rules of Engagement', 1980, 'documentary', 6);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (294, 15, 'Party 2, The (Boum 2, La)', 1971, 'fantasy', 7);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (295, 12, 'Collateral Damage', 1960, 'action', 17);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (296, 14, 'Hitch Hikers Guide to the Galaxy, The', 1802, 'horror', 12);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (297, 95, 'No Mercy', 1835, 'documentary', 2);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (298, 62, 'Loose Change: Second Edition', 1884, 'fantasy', 16);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (299, 65, 'Day the Earth Stood Still, The', 1919, 'fantasy', 8);
insert into BOOK (book_id, author_id, title, publication_year, genre, num_copies) values (300, 37, 'Crime Busters', 1924, 'action', 10);
